# Generated by Django 4.2 on 2025-11-14 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('nota', models.IntegerField(choices=[(1, '⭐ 1 estrela'), (2, '⭐⭐ 2 estrelas'), (3, '⭐⭐⭐ 3 estrelas'), (4, '⭐⭐⭐⭐ 4 estrelas'), (5, '⭐⭐⭐⭐⭐ 5 estrelas')], verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie', verbose_name='Filme')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
    ]
