# Generated by Django 4.2 on 2025-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('poster', models.TextField(verbose_name='Poster')),
                ('backdrop', models.TextField(blank=True, verbose_name='Backdrop')),
                ('elenco', models.JSONField(default=list, verbose_name='Elenco')),
                ('trailer', models.URLField(blank=True, verbose_name='Trailer')),
                ('nota_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota Média')),
                ('duracao', models.IntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-ano', 'titulo'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['titulo'], name='movies_movi_titulo_94d608_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genero'], name='movies_movi_genero_ed329c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['ano'], name='movies_movi_ano_2437ef_idx'),
        ),
    ]
